/*
 * Expense Tracker
 * Simple Expense Tracker
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Expense from './model/Expense';
import ExpenseCategory from './model/ExpenseCategory';
import CRUDOperationsApi from './api/CRUDOperationsApi';

/**
* Simple_Expense_Tracker.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ExpenseTracker = require('index'); // See note below*.
* var xxxSvc = new ExpenseTracker.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ExpenseTracker.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ExpenseTracker.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ExpenseTracker.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Expense model constructor.
     * @property {module:model/Expense}
     */
    Expense,

    /**
     * The ExpenseCategory model constructor.
     * @property {module:model/ExpenseCategory}
     */
    ExpenseCategory,

    /**
    * The CRUDOperationsApi service constructor.
    * @property {module:api/CRUDOperationsApi}
    */
    CRUDOperationsApi
};
