openapi: 3.0.1
info:
  version: 1.0.0
  title: Expense Tracker
  description: Simple Expense Tracker
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:5000/api/
paths:
  /expense-categories:
    get:
      tags:
        - Expense Categories
      description: Get Expense Categories
      operationId: getExpenseCategories
      parameters: []
      responses:
        '200':
          description: Expense categories retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/expenseCategory'
    delete:
      tags:
        - Expense Categories
      description: Delete an expense Category
      operationId: deleteExpenseCategory
      parameters: 
        - in: query
          name: Id
          schema:
            type: integer
          required: true
          description: Id of Expense Category
      responses:
        '200':
          description: Expense categories retrieved
    post:
      tags:
        - Expense Categories
      description: Add new expense Category
      operationId: addExpenseCategory
      requestBody: 
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/expenseCategory'
                  
          
      responses:
        '200':
          description: Expense categories retrieved
    put:
      tags:
        - Expense Categories
      description: Update an expense Category
      operationId: updateExpenseCategory
      requestBody: 
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/expenseCategory'
      responses:
        '200':
          description: Expense categories retrieved
        
  /expenses:
    get:
      tags:
        - Expenses
      description: Get list of expenses
      operationId: getExpenses
      parameters: []
      responses:
        '200':
          description: Expenses retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/expense'
    post:
      tags:
        - Expenses
      description: 
        Add expense
      operationId: 
        addExpense
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/expense'
      responses:
        '200':
          description: Expense added
    delete:
      tags:
        - Expenses
      description: Delete an expense 
      operationId: deleteExpense
      parameters: 
        - in: query
          name: Id
          schema:
            type: integer
          required: true
          description: Id of Expense
      responses:
        '200':
          description: Expense deleted
          
components:
  schemas:
    expense:
      type: object
      required:
        - CategoryId, Amount
      properties:
        Id: 
          type: integer
        CategoryId:
          type: integer
        Amount:
          type: number
        Date:
          type: string
        Description:
          type: string
    expenseCategory:
      type: object
      required:
        - Category
      properties:
        Category:
          type: string
        Id:
          type: number
