/*
 * Expense Tracker
 * Simple Expense Tracker
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Expense model module.
 * @module model/Expense
 * @version 1.0.0
 */
export default class Expense {
  /**
   * Constructs a new <code>Expense</code>.
   * @alias module:model/Expense
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Expense</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Expense} obj Optional instance to populate.
   * @return {module:model/Expense} The populated <code>Expense</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Expense();
      if (data.hasOwnProperty('CategoryId'))
        obj.categoryId = ApiClient.convertToType(data['CategoryId'], 'Number');
      if (data.hasOwnProperty('Amount'))
        obj.amount = ApiClient.convertToType(data['Amount'], 'Number');
      if (data.hasOwnProperty('Date'))
        obj._date = ApiClient.convertToType(data['Date'], 'String');
      if (data.hasOwnProperty('Description'))
        obj.description = ApiClient.convertToType(data['Description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} categoryId
 */
Expense.prototype.categoryId = undefined;

/**
 * @member {Number} amount
 */
Expense.prototype.amount = undefined;

/**
 * @member {String} _date
 */
Expense.prototype._date = undefined;

/**
 * @member {String} description
 */
Expense.prototype.description = undefined;

