/*
 * Expense Tracker
 * Simple Expense Tracker
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ExpenseCategory model module.
 * @module model/ExpenseCategory
 * @version 1.0.0
 */
export default class ExpenseCategory {
  /**
   * Constructs a new <code>ExpenseCategory</code>.
   * @alias module:model/ExpenseCategory
   * @class
   * @param category {String} 
   */
  constructor(category) {
    this.category = category;
  }

  /**
   * Constructs a <code>ExpenseCategory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExpenseCategory} obj Optional instance to populate.
   * @return {module:model/ExpenseCategory} The populated <code>ExpenseCategory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExpenseCategory();
      if (data.hasOwnProperty('Category'))
        obj.category = ApiClient.convertToType(data['Category'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} category
 */
ExpenseCategory.prototype.category = undefined;

