/*
 * Expense Tracker
 * Simple Expense Tracker
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ExpenseCategory from '../model/ExpenseCategory';

/**
* CRUDOperations service.
* @module api/CRUDOperationsApi
* @version 1.0.0
*/
export default class CRUDOperationsApi {

    /**
    * Constructs a new CRUDOperationsApi. 
    * @alias module:api/CRUDOperationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getExpenseCategories operation.
     * @callback moduleapi/CRUDOperationsApi~getExpenseCategoriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExpenseCategory{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Expense Categories
     * @param {module:api/CRUDOperationsApi~getExpenseCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getExpenseCategories(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ExpenseCategory;

      return this.apiClient.callApi(
        '/expense-categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}